### ISSUE TITLE
Create a landing page 

### ISSUE THREAD

**Issue by ughrima** [upes-open/OSoC-TechConnect#1]
Refer to the provided UI/UX design to create the frontend.

**Comment by Shivansh175** [comment]
Hey, I would love to create the landing page for the project. Please assign this issue to me.

**Comment by priii-25** [comment]
Hey, can I work on this?

**Comment by ughrima** [comment]
> Hey, can I work on this?

Assigned.

**Comment by Shivansh175** [comment]
@ughrima Will you provide the details to fill in or just random lorem ipsum texts to be shown there? Same questions for the logos >>

**Comment by ughrima** [comment]
> @ughrima Will you provide the details to fill in or just random lorem ipsum texts to be shown there? Same questions for the logos >>

Currently, you have two options for the landing page. You can either provide a short description that you feel would be appropriate, or you can leave it as lorem ipsum text. As for the logo, it should only consist of the word "TechConnect."

**Comment by shambhaveesrivastava12** [comment]
Hey, could you please assign it to me under oSoC'23!

**Comment by ughrima** [comment]
> Hey, could you please assign it to me under oSoC'23!

This issue is almost done hence I'll advise you to work on some other issue.
