### ISSUE TITLE
Implement a form for opportunities to be uploaded 

### ISSUE THREAD

**Issue by ughrima** [upes-open/OSoC-TechConnect#11]

**Comment by s0ham075** [comment]
I want to work on this , but before I wanted to confirm that the input field type for each of the 3 fields TITLE, KEY_DETAILS and DESCRIPTION  will be Text only or no

**Comment by ughrima** [comment]
The input field type should accommodate both numbers and alphabets.

**Comment by s0ham075** [comment]
Sure i would like to work on it

**Comment by ughrima** [comment]
> Sure i would like to work on it

Assigned.

**Comment by s0ham075** [comment]
Actually my end semester exams are going on so i couldn't contribute actively, however my exams are going to end on 26th after then I'll be able to start

**Comment by ughrima** [comment]
> Actually my end semester exams are going on so i couldn't contribute actively, however my exams are going to end on 26th after then I'll be able to start

Sure, no worries. Best of luck for your exams!

**Comment by rohin079** [comment]
I worked on this issue and created the necessary Pull Request
