### ISSUE TITLE
User authorization

### ISSUE THREAD

**Issue by ughrima** [upes-open/OSoC-TechConnect#13]
For example in UPES : 
faculty mails are in this format - name.surname@ddn.upes.ac.in
chapter mails are in this format - chapter.name@stu.upes.ac.in

**Comment by Akki019** [comment]
I can do this.

**Comment by ughrima** [comment]
> I can do this.

Assigned.

**Comment by ughrima** [comment]
> I would like to work on this issue under OSoc'23

Assigned!
