### ISSUE TITLE
Create a form for the chapter to create a post about upcoming event

### ISSUE THREAD

**Issue by ughrima** [upes-open/OSoC-TechConnect#17]
Refer to the provided UI/UX design to create frontend for this form.

**Comment by Shivansh175** [comment]
I would love to work upon this issue.

**Comment by ughrima** [comment]
> I would love to work upon this issue.

Assigned.

**Comment by Shivansh175** [comment]
@ughrima Did you check out my PR made on the issue to create a landing page in the same project??

**Comment by Shivansh175** [comment]
There is a calender in this window...is that a part of my work?

**Comment by ughrima** [comment]
> There is a calender in this window...is that a part of my work?

No that will be integrated later you can leave space for that

**Comment by Shivansh175** [comment]
What if I solve more than one issue on same PR? Will I be rewarded points for only one or all of the issues resolved?

**Comment by ughrima** [comment]
> What if I solve more than one issue on same PR? Will I be rewarded points for only one or all of the issues resolved?

See each issue has its own points depending on whether its intermediate, easy or advance. So you would be rewarded points individually for each issue you solve. And yes if you want you can solve mor than one issue on the same PR but kindly make it clear in the comments. Hope this solved your queries.

**Comment by Shivansh175** [comment]
yeah.
