### ISSUE TITLE
Create a form for admin/faculty/chapter to publish a blog 

### ISSUE THREAD

**Issue by ughrima** [upes-open/OSoC-TechConnect#18]
Refer to the provided UI/UX design to create frontend for this form.

**Comment by chshiv** [comment]
please assign me this task

**Comment by ughrima** [comment]
> please assign me this task

Assigned!

**Comment by Shivansh175** [comment]
Will u please assign me this task?

**Comment by Shivansh175** [comment]
Is this work done? If not, Please assign it to me.

**Comment by ughrima** [comment]
> Is this work done? If not, Please assign it to me.

Assigned!
