### ISSUE TITLE
Create a form to send a blog to admin for publishing and approval

### ISSUE THREAD

**Issue by ughrima** [upes-open/OSoC-TechConnect#19]
Refer to the provided UI/UX design to create frontend for this form.

**Comment by Shivansh175** [comment]
Please assign this to me.

**Comment by ughrima** [comment]
> Please assign this to me.

Assigned.

**Comment by mswat5** [comment]
hey @Shivansh175  are you working on this?

**Comment by Shivansh175** [comment]
Yes, I almost completed it.
