### ISSUE TITLE
Create a chapter page

### ISSUE THREAD

**Issue by ughrima** [upes-open/OSoC-TechConnect#2]
Refer to the provided UI/UX design to create the frontend.

**Comment by mswat5** [comment]
hey @ughrima  can you please assign it to me?

**Comment by ughrima** [comment]
> hey @ughrima can you please assign it to me?

Assigned.

**Comment by ughrima** [comment]
Hi @mswat5 ! Any progress ? If you have any doubts or anything you can always reach out.

**Comment by ughrima** [comment]
> Please assign me this issue.

Assigned.
