### ISSUE TITLE
Create a form for opportunities to be uploaded 

### ISSUE THREAD

**Issue by ughrima** [upes-open/OSoC-TechConnect#5]
Refer to the provided UI/UX design to create frontend for this form.

**Comment by Kruthardh11** [comment]
I would like to work on this

**Comment by ughrima** [comment]
> I would like to work on this

Assigned.

**Comment by Shivansh175** [comment]
I would love to work upon this issue.

**Comment by ughrima** [comment]
> I would love to work upon this issue.

Assigned
