### ISSUE TITLE
Create a navbar and footer

### ISSUE THREAD

**Issue by ughrima** [upes-open/OSoC-TechConnect#6]
Refer to the provided UI/UX design to create the frontend.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under osoc'23

**Comment by Shivansh175** [comment]
please assign it to me.

**Comment by ughrima** [comment]
> please assign it to me.

Assigned!

**Comment by Shivansh175** [comment]
What I have to do actually in this issue? Do I have to create a blank page displaying only header and footer?

**Comment by ughrima** [comment]
> What I have to do actually in this issue? Do I have to create a blank page displaying only header and footer?

Yes so that if required , in backend we can import the navbar directly like the calendar from the base file.

**Comment by Shivansh175** [comment]
okay
